import os
import glob

def enhance():
    files = glob.glob("prompts/new/*.md") + glob.glob("prompts/update/*.md")
    print(f"Discovered {len(files)} prompts for Enterprise Enhancement.")

    meta_injection = """
## Context
**Required Documents:**
- `project-context.md`

## Missing Information Handling
If required inputs are missing, the AI Agent must:
1. Identify gaps.
2. List missing inputs.
3. Ask clarifying questions.
4. Explain the impact of the missing data.
**Rule:** Never silently assume undocumented constraints.

## AI Agent Collaboration
**Consumes:** Project Context and dependencies
**Produces:** Target output document
**Next Recommended Prompt:** Proceed to the next logical stage in the SDLC pipeline.
"""

    prompt_injection = """
### Detail Expansion Rules
Every document generated by this prompt MUST explicitly include the following structured sections:
- **Assumptions:** What undocumented facts were relied upon.
- **Constraints:** What technical or business limitations exist.
- **Risks:** What could go wrong and mitigation strategies.
- **Dependencies:** What other systems or documents this relies on.
- **Open Questions:** What requires human clarification before proceeding.
- **Future Enhancements:** What can be added in later iterations.

### Documentation Standards
- Use strict Markdown formatting with clear hierarchies.
- Include **Mermaid.js Diagrams** (Flowcharts, Sequence Diagrams, ER Diagrams) where appropriate to visualize complex systems.
- Maintain strict **Traceability** from Business Requirement → Product Requirement → User Story → Technical Requirement → Test Case.
"""

    for filepath in files:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()

        # 1. Inject meta sections before "## Output Location" 
        if "## Context" not in content and "## Output Location" in content:
            content = content.replace("## Output Location", meta_injection.strip() + "\n\n## Output Location")

        # 2. Inject prompt expansion rules inside the "Complete Prompt Content"
        # Inject it right before "# AI Agent Operating Rules"
        if "### Detail Expansion Rules" not in content and "# AI Agent Operating Rules" in content:
            content = content.replace("# AI Agent Operating Rules", prompt_injection.strip() + "\n\n# AI Agent Operating Rules")

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)

    print("✅ All 67 prompts successfully upgraded to Enterprise-Grade standards.")

if __name__ == "__main__":
    enhance()
