import os
import glob

def categorize_output_path(filename):
    name = filename.lower()
    
    if name.startswith("review-"):
        return f"/docs/reviews/{name.replace('review-', '')}"
    elif name.startswith("audit-"):
        return f"/docs/audits/{name.replace('audit-', '')}"
    
    # Strip prefixes for categorization
    out_name = name
    for prefix in ["create-", "update-", "generate-"]:
        if out_name.startswith(prefix):
            out_name = out_name[len(prefix):]
            break
            
    if "requirement" in name or "discovery" in name or "business" in name or "user-stories" in name:
        return f"/docs/requirements/{out_name}"
    elif "architecture" in name or "database" in name or "security-design" in name or "deployment-architecture" in name:
        return f"/docs/architecture/{out_name}"
    elif "flow" in name or "screen" in name or "wireframe" in name or "journey" in name or "design" in name:
        return f"/docs/design/{out_name}"
    elif "test" in name:
        return f"/docs/testing/{out_name}"
    elif "release" in name or "deployment-checklist" in name:
        return f"/docs/releases/{out_name}"
    elif "implementation" in name or "sprint" in name or "development" in name or "tasks" in name or "debt" in name:
        return f"/docs/planning/{out_name}"
    elif "project-" in name:
        return f"/docs/foundation/{out_name}"
    
    return f"/docs/general/{out_name}"

def evolve():
    files = glob.glob("prompts/new/*.md") + glob.glob("prompts/update/*.md")
    print(f"Evolving {len(files)} prompts...")

    evolution_injection = """
### Cross Document Consistency & Dependency Validation
Before generating any output, you MUST verify the existence of all prerequisite documents (e.g., PRD, TRD, Architecture Docs). 
- **If missing:** Stop immediately and generate a Missing Dependency Report.
- **If existing:** Cross-check them for inconsistencies. Do not continue if contradictory instructions exist.

### Quality Gates & Traceability
You must perform a self-review against these required checks: Completeness, Consistency, Dependency Validation, Risk Analysis, Assumption Review, Documentation Quality.
- Include a **Traceability Matrix** linking Business Goals → Requirements → Technical Tasks → Test Cases.

### Mandatory Embedded Sections
Every document generated by this prompt MUST explicitly include:
- **Decision Log:** Key Decisions, Alternatives Considered, Decision Rationale, Future Review Date.
- **Risk Analysis:** Risks, Risk Severity, Mitigation Strategy, Monitoring Strategy.
- **Repository Knowledge Preservation:** Never overwrite existing architecture or constraint decisions without explicit justification.

### AI Agent Memory Handoff
At the very end of your generated document, you MUST produce an Agent Handoff block:
```text
---
# Agent Summary
**Documents Consumed:** [List of docs read]
**Documents Produced:** [List of docs created]
**Open Questions:** [List of unresolved issues]
**Recommended Next Prompt:** [Next logical prompt to execute]
```
"""

    update_strategy_injection = """
### Document Update Strategy
As this is an update task, your generated document MUST include a preamble containing:
- **Change Summary**
- **Sections Modified**
- **Impact Analysis**
- **Backward Compatibility Review**
- **Cross Document Impact Review**
- **Follow-Up Actions**
"""

    for filepath in files:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()

        filename = os.path.basename(filepath)
        new_out_path = categorize_output_path(filename)
        
        # 1. Update Output Routing
        # Find the line under ## Output Location and replace it
        lines = content.split('\n')
        for i, line in enumerate(lines):
            if line.startswith("## Output Location"):
                if i + 1 < len(lines) and lines[i+1].startswith("`"):
                    lines[i+1] = f"`{new_out_path}`"
                break
        content = '\n'.join(lines)

        # 2. Inject Evolution Rules
        if "### Cross Document Consistency" not in content and "# AI Agent Operating Rules" in content:
            content = content.replace("# AI Agent Operating Rules", evolution_injection.strip() + "\n\n# AI Agent Operating Rules")

        # 3. Inject Update Strategy for prompts in /update/
        if "update/" in filepath and "### Document Update Strategy" not in content and "# AI Agent Operating Rules" in content:
             content = content.replace("# AI Agent Operating Rules", update_strategy_injection.strip() + "\n\n# AI Agent Operating Rules")

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)

    print("✅ Prompt Evolution Complete. Repository mapped and categorized.")

if __name__ == "__main__":
    evolve()
